export const USER_LOGGED = "USER_LOGGED";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_YEAR_COMICS = "GET_YEAR_COMICS";
export const OPEN_SEARCH_BOX = "OPEN_SEARCH_BOX";
export const CLOSE_SEARCH_BOX = "CLOSE_SEARCH_BOX";
